application: snucircle
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  static_files: self.html
  upload: self.html
  mime_type: text/html

- url: /idea.html
  static_files: idea.html
  upload: idea.html
  mime_type: text/html

- url: /photo.html
  static_files: photo.html
  upload: photo.html
  mime_type: text/html

- url: /maps.html
  static_files: maps.html
  upload: maps.html
  mime_type: text/html

- url: /static/css
  static_dir: static/css
  mime_type: text/css

- url: /static/js
  static_dir: static/js
  mime_type: text/javascript

- url: /static/res/img
  static_dir: static/res/img
  mime_type: image/png